#! python3
# multi_clip_board.py - Saves and loads pieces of text to the clipboard.
# Usage: py.exe multi_clip_board.py save <keyword> - Saves clipboard to keyword.
#        py.exe multi_clip_board.py list - Loads all keywords to clipboard.
#        py.exe multi_clip_board.py <keyword> - Loads keyword to clipboard.

import sys, pyperclip, shelve

# Create shelf file to store clipboard data.
mcb_shelf = shelve.open('mcb2')

# Save clipboard content to keyword.
if len(sys.argv) == 3 and sys.argv[1].lower() == 'save':
    mcb_shelf[sys.argv[2]] = pyperclip.paste()
# Load all keywords to clipboard.
elif len(sys.argv) == 2:
    if sys.argv[1].lower() == 'list':
        pyperclip.copy(str(list(mcb_shelf.keys())))
    # Load keyword to clipboard.
    elif sys.argv[1] in mcb_shelf:
        pyperclip.copy(mcb_shelf[sys.argv[1]])

mcb_shelf.close()
