#! python3
# A program which asks the user to provide a password
# explains the strength of that password and keeps asking the
# user for a password until one that meets high password
# complexity (strong strength) requirements as defined below are given.
# The program also writes a file to store all passwords provided
# to the program.

import re

file_name = 'passwords.txt'
# Password complexity requirements below.
uppercase_letter_regex = re.compile(r"[A-Z]") # Password must contain >= 1 uppercase letter.
lowercase_letter_regex = re.compile(r"[a-z]") # Password must contain >= 1 lowercase letter.
digit_regex = re.compile(r"\d") # Password must contain >= digit. 
weak_pw_count = 1 # Count of password checks before strong password is provided.


# Creates a file to store all passwords.
def write_to_file(message):
    with open(file_name, 'a') as f_object:
        f_object.write(message + "\n")


# Stores all written passwords into the file.
def create_file():
    with open(file_name, 'w') as f_object:
        f_object.write("Welcome to Anthony's password tester!\n")
        f_object.write("Below is a record of all password check attempts:\n")


# Checks if password meets complexity requirements.
def is_password_strong(password):
    if len(password) < 8:
        return False
    if uppercase_letter_regex.search(password) is None:
        return False
    if lowercase_letter_regex.search(password) is None:
        return False
    if digit_regex.search(password) is None:
        return False
    return True


# Asks user for password until a strong enough password is given.
print("Welcome to Anthony's password tester!")
create_file()
print("Please enter your password below to see if it is strong or weak.\n")
while True:
    password = input("Password: ")
    is_password_strong_result = is_password_strong(password)
    if is_password_strong_result:
        print("Your password is strong!")
        write_to_file("Strong password: " + password)
        break
    else:
        print("Your password is bad and you should feel bad!")
        write_to_file("Weak password " + str(weak_pw_count) + ": " + password)
        weak_pw_count += 1
        print("Type a strong one please.\n")
print("You have a good password, you have nothing to worry about!\n")
input('Press enter to exit.')
